Closes #65 delete button
team-street-cred/acebook-team-street-cred pull request #90
Opened 2019-03-04 16:08 UTC by RubyKobayashi

2019-03-04 17:06 UTC, Estevenson1994 commented
Magical

2019-03-04 17:07 UTC, Estevenson1994 approved these changes

2019-03-04 17:11 UTC, Estevenson1994 commented on app/controllers/posts_controller.rb
> +  def destroy
Maybe this could be done in the view, where by the edit/delete buttons are only visable to those who created the post?

2019-03-04 17:15 UTC, david-mears commented on spec/controllers/posts_controller_spec.rb
> +
We already have a post_controller_spec.rb - let's combine!

2019-03-04 17:16 UTC, david-mears commented on spec/features/user_can_delete_posts_spec.rb
> +  xscenario 'Users can only delete their own posts' do
I'd like this test to be activated (not pending) when we run it through travis.

2019-03-04 17:19 UTC, david-mears commented on spec/features/user_can_delete_posts_spec.rb
> +    expect(page).to have_css("img[src*='test2.jpg']")
Hmm, why are we testing that certain images are here?

2019-03-04 17:21 UTC, david-mears commented on spec/views/posts/index.html.erb_spec.rb
> +end
This looks like it doesn't test anything

2019-03-04 17:21 UTC, david-mears commented on spec/views/posts/show.html.erb_spec.rb
> +    render
This too looks overly simplistic

2019-03-04 17:22 UTC, david-mears requested changes
I've left some comments

2019-03-04 18:03 UTC, david-mears commented on spec/controllers/posts_controller_spec.rb
> +
thanks, resolved

2019-03-05 11:26 UTC, david-mears approved these changes

2019-03-05 11:35 UTC, merged